channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - admixtools=7.0.2
  - bcftools=1.11
  - bedtools=2.29.2
  - biopython=1.78
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - click=7.1.2
  - curl=7.86.0
  - matplotlib=3.3.2
  - msprime=0.7.4
  - numba=0.51.2
  - numpy=1.19.2
  - openssl=1.1.1t
  - pandas=1.1.3
  - parallel=20230122
  - pip=20.2.4
  - plink=1.90b6.21
  - pot=0.7.0
  - progressbar=2.5
  - pysam=0.16.0.1
  - python=3.8.15
  - pyyaml=5.3.1
  - r-adaptivetau=2.2_3
  - r-argparser=0.6
  - r-base=3.6.3
  - r-bedr=1.0.7
  - r-bookdown=0.21
  - r-coda=0.19_4
  - r-curl=3.3
  - r-daag=1.22.1
  - r-data.table=1.13.2
  - r-desolve=1.28
  - r-directlabels=2021.1.13
  - r-dplyr=1.0.2
  - r-expm=0.999_5
  - r-fitr=0.1
  - r-ggplot2=3.3.2
  - r-ggpubr=0.4.0
  - r-ggrastr=0.2.1
  - r-ggrepel=0.9.1
  - r-ggridges=0.5.2
  - r-googlesheets4=0.2.0
  - r-gtools=3.8.2
  - r-hmisc=4.5_0
  - r-jquerylib=0.1.4
  - r-jsonlite=1.7.1
  - r-kableextra=1.3.1
  - r-knitr=1.30
  - r-plotly=4.9.2.1
  - r-purrr=0.3.4
  - r-r.utils=2.10.1
  - r-rcppcnpy=0.2.10
  - r-rcpproll=0.3.0
  - r-reader=1.0.6
  - r-readr=1.4.0
  - r-rjson=0.2.20
  - r-rmarkdown=2.8
  - r-rsconnect=0.8.16
  - r-scales=1.1.1
  - r-shadowtext=0.0.8
  - r-stringr=1.4.0
  - r-styler=1.3.2
  - r-tidyr=1.1.2
  - r-vcfr=1.12.0
  - r-viridis=0.5.1
  - r-zoo=1.8_6
  - requests=2.24.0
  - scipy=1.5.2
  - snakefmt=0.2.0
  - snakemake=5.26.1
  - tqdm=4.51.0
